version: '3.7'

services:
  portainer:
    image: portainer/portainer:latest
    restart: always
    env_file: &envFile
      - .env
    ports:
      - 9000:9000
    volumes:
      - PortainerData:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks: &network
      - nginxProxy

  app:
    build:
      context: .
      dockerfile: Dockerfile/app.Dockerfile
    command: php -S 0.0.0.0:${APP_PORT_INTERNAL} -t public
    working_dir: /app
    env_file: *envFile
    environment:
      VIRTUAL_HOST: test.local
    volumes:
      - .:/app
    ports:
      - ${APP_PORT_EXTERNAL}:${APP_PORT_INTERNAL}
    depends_on:
      - mysql5
    networks: *network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file: *envFile
    environment:
      PMA_HOST: mysql5
    ports:
      - ${PHPMYADMIN_PORT_EXTERNAL}:80
    depends_on:
      - mysql5
    networks: *network

  mysql5:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=512M
    env_file: *envFile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - MysqlDb:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
      - ${MYSQL_SOCKET_PORT}:33060
    networks: *network

  nginxProxy:
    image: jwilder/nginx-proxy:latest
    env_file: *envFile
    ports:
      - ${NGINX_PROXY_PORT}:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks: *network

  # apache:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile/apache.Dockerfile

  mongo:
    image: mongo:latest
    env_file: *envFile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - MongoDb:/data/db
    ports:
      - ${MONGO_PORT}:27017
    networks: *network

volumes:
  PortainerData:
    external:
      name: PortainerData
  MysqlDb:
    external:
      name: MysqlDb
  MongoDb:
    external:
      name: MongoDb

networks:
  nginxProxy:
    external:
      name: nginxProxy
