version: "3.7"

services:
  portainer:
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - portainerData:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginxProxy

  app:
    build:
      context: .
      dockerfile: Dockerfile/app.Dockerfile
    command: php -S 0.0.0.0:${APP_PORT_INTERNAL} -t public
    working_dir: /app
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: test.local
    volumes:
      - .:/app
    ports:
      - ${APP_PORT_EXTERNAL}:${APP_PORT_INTERNAL}
    depends_on:
      - mysql5
    networks:
      - nginxProxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - .env
    environment:
      PMA_HOST: mysql5
    ports:
      - ${PHPMYADMIN_PORT_EXTERNAL}:80
    depends_on:
      - mysql5
    networks:
      - nginxProxy

  mysql5:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=512M
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - MysqlDb:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
      - ${MYSQL_SOCKET_PORT}:33060
    networks:
      - nginxProxy

  nginxProxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - nginxProxy

  apache:
    build:
      context: .
      dockerfile: Dockerfile/apache.Dockerfile

volumes:
  MysqlDb:
    external:
      name: MysqlDb
  portainerData:
    external:
      name: portainerData

networks:
  nginxProxy:
    external:
      name: nginxProxy
