version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    environment:
      LETSENCRYPT_HOST: portainer.dualwind.xyz
      VIRTUAL_HOST: portainer.dualwind.xyz
      VIRTUAL_PORT: 9000
    expose:
      - 9000
    volumes:
      - PortainerData:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks: &network
      - nginxProxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql5
      LETSENCRYPT_HOST: phpmyadmin.dualwind.xyz
      VIRTUAL_HOST: phpmyadmin.dualwind.xyz
      VIRTUAL_PORT: 80
    expose:
      - 80
    depends_on:
      - mysql5
    networks: *network

  mysql5:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=512M
    env_file:
      - ./env/mysql.env
    volumes:
      - MysqlDb:/var/lib/mysql
      - ./database:/database
    ports:
      - 3306:3306
    networks: *network

  nginxProxy:
    image: jwilder/nginx-proxy:latest
    restart: always
    container_name: nginxProxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: 'true'
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginxCerts:/etc/nginx/certs
      - nginxVhostd:/etc/nginx/vhost.d
      - nginxHtml:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: *network

  sslGenerator:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginxProxy
      NGINX_DOCKER_GEN_CONTAINER: nginxProxy
      DEFAULT_EMAIL: thanhson_it201@yahoo.com
    volumes:
      - nginxCerts:/etc/nginx/certs
      - nginxVhostd:/etc/nginx/vhost.d
      - nginxHtml:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: *network

  redis:
    image: bitnami/redis:latest
    restart: always
    env_file:
      - ./env/redis.env
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb --maxmemory-policy allkeys-lru
    networks: *network
    ports:
      - 6379:6379
    volumes:
      - RedisData:/bitnami/redis/data

  cadvisor:
    build:
      context: .
      dockerfile: Dockerfile/cadvisor.Dockerfile
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks: *network

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks: *network

  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      LETSENCRYPT_HOST: grafana.dualwind.xyz
      VIRTUAL_HOST: grafana.dualwind.xyz
      VIRTUAL_PORT: 3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks: *network

volumes:
  PortainerData:
    external:
      name: PortainerData
  MysqlDb:
    external:
      name: MysqlDb
  RedisData:
    external:
      name: RedisData
  MongoDb:
    external:
      name: MongoDb
  nginxCerts:
  nginxHtml:
  nginxVhostd:
  grafana:

networks:
  nginxProxy:
    external:
      name: nginxProxy
