version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile/app.Dockerfile
    command: php -S 0.0.0.0:${APP_PORT_INTERNAL} -t public
    working_dir: /app
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    volumes:
      - .:/app
    ports:
      - ${APP_PORT_EXTERNAL}:${APP_PORT_INTERNAL}
    links:
      - mysql:db
    networks:
      - asgard

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - ${PHPMYADMIN_PORT_EXTERNAL}:${PHPMYADMIN_PORT_INTERNAL}
    links:
      - mysql8:db
    networks:
      - asgard

  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - MysqlDb:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
      - ${MYSQL_SOCKET_PORT}:${MYSQL_SOCKET_PORT}
    networks:
      - asgard

  mysql8:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - asgard

volumes:
  MysqlDb:
    name: MysqlDb

networks:
  asgard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24